# Generated by Django 4.0.2 on 2022-12-05 13:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 13, 49, 4, 354717, tzinfo=utc)),
        ),
    ]
