# Generated by Django 4.0.2 on 2024-06-30 17:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_datetime_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 30, 17, 23, 37, 713884, tzinfo=utc)),
        ),
    ]
